name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "103.217.252.147"
          username: "runcloud"
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/runcloud/webapps/rockflix/current
            git fetch --all
            git reset --hard origin/main
            cp .env.production.rockflix .env.production
            npm install
            npm run build
            pm2 restart rockflix
